api_token_env: CROWDIN_PERSONAL_TOKEN
project_id_env: CROWDIN_PROJECT_ID
preserve_hierarchy: true
files:
  - source: /**/zh-hant.*
    translation: /%original_path%/%two_letters_code%.%file_extension%
